static class GemSystemID
{
    // Event ID 
    public const int GEM_PP_CHANGE = 3;             //UINT_4    GemProcessProgramChange
    public const int GEM_CONTROL_STATE_LOCAL = 8;   //UINT_4GemControlStateLocal
    public const int GEM_CONTROL_STATE_REMOTE = 9;  //UINT_4GemControlStateRemote
    public const int GEM_EQ_CONST_CHANGED = 20;     //UINT_4    GemEqConstChanged
    public const int GEM_MESSAGE_RECOGNITION = 21;  //UINT_4GemMessageRecognition
    public const int GEM_EQP_OFF_LINE = 22;         //UINT_4    GemEqpOffLine
    public const int GEM_SPOOLING_ACTIVED = 23;     //UINT_4    GemSpoolingActived
    public const int GEM_SPOOLING_DEACTIVED = 24;       //UINT_4GemSpoolingDeactived
    public const int GEM_SPOOL_TRANSMIT_FAILURE = 25;                             //UINT_4GemSpoolTransmitFailure

    // SV ID 
    public const int LICENSE_CODE_SVID = 1;      //ASCII     License Code
    public const int LICENSE_STATUS_SVID = 2;    //UINT_1    License Status
    public const int GEM_CLOCK = 3;              //ASCII     GemClock
    public const int GEM_CONTROL_STATE = 4;      //UINT_1    GemControlState
    public const int GEM_LINK_STATE = 5;         //UINT_1    GemLinkState
    public const int GEM_COMM_MODE = 6;          //UINT_1    SECSCommunicationMode
    public const int GEM_PREVIOUS_CEID = 11;     //UINT_4    GemPreviousCEID
    public const int GEM_OFF_LINE_SUB_STATE_SV = 12;                              //UINT_1GemOffLineSubState
    public const int GEM_PREVIOUS_CONTROL_STATE = 13;                             //UINT_1GemPreviousControlState
    public const int GEM_PREVIOUS_PROCESS_STATE = 14;                             //UINT_1GemPreviousProcessState
    public const int GEM_PROCESS_STATE = 15;     //UINT_1    GemProcessState
    public const int GEM_MDLN = 24;              //ASCII     GemMDLN
    public const int GEM_SOFTREV = 25;           //ASCII     GemSOFTREV
    public const int GEM_ALARM_ENABLED = 39;     //LIST      List GemAlarmsEnabled
    public const int GEM_ALARM_SET = 40;         //LIST      List GemAlarmSet
    public const int GEM_EVENT_ENABLED = 41;     //LIST      List GemEventsEnabled
    public const int GEM_PP_EXEC_NAME = 42;      //ASCII     GemPPExecName
    public const int PP_FORMAT = 43;             //UINT_1    PPFormat
    public const int GEM_ECID_CHANGED = 46;      //UINT_4    GemECIDChanged
    public const int GEM_EC_VALUE_CHANGED = 47;  //ASCII     ECValueChanged
    public const int GEM_PREVIOUS_EC_VALUE = 48; //ASCII     PreviousECValue
    public const int GEM_SPOOL_COUNT_ACTUAL = 53;                                 //UINT_4GemSpoolCountActual
    public const int GEM_SPOOL_COUNT_TOTAL = 54; //UINT_4    GemSpoolCountTotal
    public const int GEM_SPOOL_FULL_TIME = 55;   //ASCII     GemSpoolFullTime
    public const int GEM_SPOOL_START_TIME = 57;  //ASCII     GemSpoolStartTime
    public const int GEM_SPOOL_STATE = 58;       //UINT_1    GemSpoolState
    public const int GEM_SOFTWARE_REVISION = 80; //ASCII     Gem Soft Ware Revision

    // DV ID 
    public const int GEM_DV_PP_CHANGE_NAME = 9;  //ASCII     GemPPChangeName
    public const int GEM_DV_PP_CHANGE_STATUS = 10;                                //UINT_1GemPPChangeStatus
    public const int GEM_DV_ALARM_ID = 38;       //UINT_4    GemAlarmID
    public const int GEM_DV_ECID_CHANGED = 46;   //UINT_4    GemECIDChanged
    public const int GEM_DV_EC_VALUE_CHANGED = 47;                                //ASCIIECValueChanged
                                                                                  //* E87 received data area =======================
    public const int E87_CONTENT_MAP = 1101;     //LIST      *E87 ContentMap
    public const int E87_CAPACITY = 1102;        //UINT_1    *E87 Capacity
    public const int E87_SLOT_MAP = 1103;        //LIST      *E87 SlotMap
    public const int E87_CTMAP_SUB_LIST1 = 1201; //LIST      *E87 ContentMap sub list1
    public const int E87_CTMAP_SUB_LIST2 = 1202; //LIST      *E87 ContentMap sub list2
    public const int E87_CTMAP_SUB_LIST3 = 1203; //LIST      *E87 ContentMap sub list3
    public const int E87_CTMAP_SUB_LIST4 = 1204; //LIST      *E87 ContentMap sub list4
    public const int E87_CTMAP_SUB_LIST5 = 1205; //LIST      *E87 ContentMap sub list5
    public const int E87_CTMAP_SUB_LIST6 = 1206; //LIST      *E87 ContentMap sub list6
    public const int E87_CTMAP_SUB_LIST7 = 1207; //LIST      *E87 ContentMap sub list7
    public const int E87_CTMAP_SUB_LIST8 = 1208; //LIST      *E87 ContentMap sub list8
    public const int E87_CTMAP_SUB_LIST9 = 1209; //LIST      *E87 ContentMap sub list9
    public const int E87_CTMAP_SUB_LIST10 = 1210;//LIST     *E87 ContentMap sub list10
    public const int E87_CTMAP_SUB_LIST11 = 1211;//LIST     *E87 ContentMap sub list11
    public const int E87_CTMAP_SUB_LIST12 = 1212;//LIST     *E87 ContentMap sub list12
    public const int E87_CTMAP_SUB_LIST13 = 1213;//LIST     *E87 ContentMap sub list13
    public const int E87_CTMAP_SUB_LIST14 = 1214;//LIST     *E87 ContentMap sub list14
    public const int E87_CTMAP_SUB_LIST15 = 1215;//LIST     *E87 ContentMap sub list15
    public const int E87_CTMAP_SUB_LIST16 = 1216;//LIST     *E87 ContentMap sub list16
    public const int E87_CTMAP_SUB_LIST17 = 1217;//LIST     *E87 ContentMap sub list17
    public const int E87_CTMAP_SUB_LIST18 = 1218;//LIST     *E87 ContentMap sub list18
    public const int E87_CTMAP_SUB_LIST19 = 1219;//LIST     *E87 ContentMap sub list19
    public const int E87_CTMAP_SUB_LIST20 = 1220;//LIST     *E87 ContentMap sub list20
    public const int E87_CTMAP_SUB_LIST21 = 1221;//LIST     *E87 ContentMap sub list21
    public const int E87_CTMAP_SUB_LIST22 = 1222;//LIST     *E87 ContentMap sub list22
    public const int E87_CTMAP_SUB_LIST23 = 1223;//LIST     *E87 ContentMap sub list23
    public const int E87_CTMAP_SUB_LIST24 = 1224;//LIST     *E87 ContentMap sub list24
    public const int E87_CTMAP_SUB_LIST25 = 1225;//LIST     *E87 ContentMap sub list25
    public const int E87_CTMAP_LOTID1 = 1301;    //ASCII     *E87 ContentMap LotID 1
    public const int E87_CTMAP_LOTID2 = 1302;    //ASCII     *E87 ContentMap LotID 2
    public const int E87_CTMAP_LOTID3 = 1303;    //ASCII     *E87 ContentMap LotID 3
    public const int E87_CTMAP_LOTID4 = 1304;    //ASCII     *E87 ContentMap LotID 4
    public const int E87_CTMAP_LOTID5 = 1305;    //ASCII     *E87 ContentMap LotID 5
    public const int E87_CTMAP_LOTID6 = 1306;    //ASCII     *E87 ContentMap LotID 6
    public const int E87_CTMAP_LOTID7 = 1307;    //ASCII     *E87 ContentMap LotID 7
    public const int E87_CTMAP_LOTID8 = 1308;    //ASCII     *E87 ContentMap LotID 8
    public const int E87_CTMAP_LOTID9 = 1309;    //ASCII     *E87 ContentMap LotID 9
    public const int E87_CTMAP_LOTID10 = 1310;   //ASCII     *E87 ContentMap LotID 10
    public const int E87_CTMAP_LOTID11 = 1311;   //ASCII     *E87 ContentMap LotID 11
    public const int E87_CTMAP_LOTID12 = 1312;   //ASCII     *E87 ContentMap LotID 12
    public const int E87_CTMAP_LOTID13 = 1313;   //ASCII     *E87 ContentMap LotID 13
    public const int E87_CTMAP_LOTID14 = 1314;   //ASCII     *E87 ContentMap LotID 14
    public const int E87_CTMAP_LOTID15 = 1315;   //ASCII     *E87 ContentMap LotID 15
    public const int E87_CTMAP_LOTID16 = 1316;   //ASCII     *E87 ContentMap LotID 16
    public const int E87_CTMAP_LOTID17 = 1317;   //ASCII     *E87 ContentMap LotID 17
    public const int E87_CTMAP_LOTID18 = 1318;   //ASCII     *E87 ContentMap LotID 18
    public const int E87_CTMAP_LOTID19 = 1319;   //ASCII     *E87 ContentMap LotID 19
    public const int E87_CTMAP_LOTID20 = 1320;   //ASCII     *E87 ContentMap LotID 20
    public const int E87_CTMAP_LOTID21 = 1321;   //ASCII     *E87 ContentMap LotID 21
    public const int E87_CTMAP_LOTID22 = 1322;   //ASCII     *E87 ContentMap LotID 22
    public const int E87_CTMAP_LOTID23 = 1323;   //ASCII     *E87 ContentMap LotID 23
    public const int E87_CTMAP_LOTID24 = 1324;   //ASCII     *E87 ContentMap LotID 24
    public const int E87_CTMAP_LOTID25 = 1325;   //ASCII     *E87 ContentMap LotID 25
    public const int E87_CTMAP_SUBSTID1 = 1401;  //ASCII     *E87 ContentMap SubstID 1
    public const int E87_CTMAP_SUBSTID2 = 1402;  //ASCII     *E87 ContentMap SubstID 2
    public const int E87_CTMAP_SUBSTID3 = 1403;  //ASCII     *E87 ContentMap SubstID 3
    public const int E87_CTMAP_SUBSTID4 = 1404;  //ASCII     *E87 ContentMap SubstID 4
    public const int E87_CTMAP_SUBSTID5 = 1405;  //ASCII     *E87 ContentMap SubstID 5
    public const int E87_CTMAP_SUBSTID6 = 1406;  //ASCII     *E87 ContentMap SubstID 6
    public const int E87_CTMAP_SUBSTID7 = 1407;  //ASCII     *E87 ContentMap SubstID 7
    public const int E87_CTMAP_SUBSTID8 = 1408;  //ASCII     *E87 ContentMap SubstID 8
    public const int E87_CTMAP_SUBSTID9 = 1409;  //ASCII     *E87 ContentMap SubstID 9
    public const int E87_CTMAP_SUBSTID10 = 1410; //ASCII     *E87 ContentMap SubstID 10
    public const int E87_CTMAP_SUBSTID11 = 1411; //ASCII     *E87 ContentMap SubstID 11
    public const int E87_CTMAP_SUBSTID12 = 1412; //ASCII     *E87 ContentMap SubstID 12
    public const int E87_CTMAP_SUBSTID13 = 1413; //ASCII     *E87 ContentMap SubstID 13
    public const int E87_CTMAP_SUBSTID14 = 1414; //ASCII     *E87 ContentMap SubstID 14
    public const int E87_CTMAP_SUBSTID15 = 1415; //ASCII     *E87 ContentMap SubstID 15
    public const int E87_CTMAP_SUBSTID16 = 1416; //ASCII     *E87 ContentMap SubstID 16
    public const int E87_CTMAP_SUBSTID17 = 1417; //ASCII     *E87 ContentMap SubstID 17
    public const int E87_CTMAP_SUBSTID18 = 1418; //ASCII     *E87 ContentMap SubstID 18
    public const int E87_CTMAP_SUBSTID19 = 1419; //ASCII     *E87 ContentMap SubstID 19
    public const int E87_CTMAP_SUBSTID20 = 1420; //ASCII     *E87 ContentMap SubstID 20
    public const int E87_CTMAP_SUBSTID21 = 1421; //ASCII     *E87 ContentMap SubstID 21
    public const int E87_CTMAP_SUBSTID22 = 1422; //ASCII     *E87 ContentMap SubstID 22
    public const int E87_CTMAP_SUBSTID23 = 1423; //ASCII     *E87 ContentMap SubstID 23
    public const int E87_CTMAP_SUBSTID24 = 1424; //ASCII     *E87 ContentMap SubstID 24
    public const int E87_CTMAP_SUBSTID25 = 1425; //ASCII     *E87 ContentMap SubstID 25
    public const int E87_SLOT_MAP_1 = 1501;      //UINT_1    *E87 SlotMap 1
    public const int E87_SLOT_MAP_2 = 1502;      //UINT_1    *E87 SlotMap 
    public const int E87_SLOT_MAP_3 = 1503;      //UINT_1    *E87 SlotMap 
    public const int E87_SLOT_MAP_4 = 1504;      //UINT_1    *E87 SlotMap 
    public const int E87_SLOT_MAP_5 = 1505;      //UINT_1    *E87 SlotMap 
    public const int E87_SLOT_MAP_6 = 1506;      //UINT_1    *E87 SlotMap 
    public const int E87_SLOT_MAP_7 = 1507;      //UINT_1    *E87 SlotMap 
    public const int E87_SLOT_MAP_8 = 1508;      //UINT_1    *E87 SlotMap 
    public const int E87_SLOT_MAP_9 = 1509;      //UINT_1    *E87 SlotMap 
    public const int E87_SLOT_MAP_10 = 1510;     //UINT_1    *E87 SlotMap 
    public const int E87_SLOT_MAP_11 = 1511;     //UINT_1    *E87 SlotMap 
    public const int E87_SLOT_MAP_12 = 1512;     //UINT_1    *E87 SlotMap 
    public const int E87_SLOT_MAP_13 = 1513;     //UINT_1    *E87 SlotMap 
    public const int E87_SLOT_MAP_14 = 1514;     //UINT_1    *E87 SlotMap 
    public const int E87_SLOT_MAP_15 = 1515;     //UINT_1    *E87 SlotMap 
    public const int E87_SLOT_MAP_16 = 1516;     //UINT_1    *E87 SlotMap 
    public const int E87_SLOT_MAP_17 = 1517;     //UINT_1    *E87 SlotMap 
    public const int E87_SLOT_MAP_18 = 1518;     //UINT_1    *E87 SlotMap 
    public const int E87_SLOT_MAP_19 = 1519;     //UINT_1    *E87 SlotMap 
    public const int E87_SLOT_MAP_20 = 1520;     //UINT_1    *E87 SlotMap 
    public const int E87_SLOT_MAP_21 = 1521;     //UINT_1    *E87 SlotMap 
    public const int E87_SLOT_MAP_22 = 1522;     //UINT_1    *E87 SlotMap 
    public const int E87_SLOT_MAP_23 = 1523;     //UINT_1    *E87 SlotMap 
    public const int E87_SLOT_MAP_24 = 1524;     //UINT_1    *E87 SlotMap 
    public const int E87_SLOT_MAP_25 = 1525;     //UINT_1    *E87 SlotMap 
    public const int E87_ACCESS_CHG_PTN_NUMBER = 1530;                            //UINT_1*E87 Access Change PTN  Number
    public const int E87_ACCESS_CHG_PTN_1 = 1531;                                 //UINT_1*E87 Access Change PTN 1
    public const int E87_ACCESS_CHG_PTN_2 = 1532;                                 //UINT_1*E87 Access Change PTN 2
    public const int E87_ACCESS_CHG_PTN_3 = 1533;                                 //UINT_1*E87 Access Change PTN 3
    public const int E87_ACCESS_CHG_PTN_4 = 1534;                                 //UINT_1*E87 Access Change PTN 4
    public const int E87_ACCESS_CHG_PTN_5 = 1535;                                 //UINT_1*E87 Access Change PTN 5
    public const int E87_ACCESS_CHG_PTN_6 = 1536;                                 //UINT_1*E87 Access Change PTN 6
    public const int E87_ACCESS_CHG_PTN_7 = 1537;                                 //UINT_1*E87 Access Change PTN 7
    public const int E87_ACCESS_CHG_PTN_8 = 1538;                                 //UINT_1*E87 Access Change PTN 8
                                                                                  //* E40  received data area======================
    public const int E40_PJ_CREATE_PRJOBID = 1601;                                //ASCII*E40 PJ create PRJOBID
    public const int E40_PJ_CREATE_CARRIER_QUANTITY = 1602;                       //UINT_1*E40 PJ create carrier Quantity 
    public const int E40_PJ_CREATE_CARRIER1_ID = 1603;                            //ASCII*E40 PJ create carrier ID
    public const int E40_PJ_CREATE_SLOT_NUMBER = 1604;                            //UINT_1*E40 PJ create slot number 
    public const int E40_PJ_CREATE_PRRECIPEMETHOD = 1605;                         //UINT_1*E40 PJ create recipe method (not support
    public const int E40_PJ_CREATE_RCPSPEC = 1606;                                //ASCII*E40 PJ create recipe spec
    public const int E40_PJ_CREATE_PRPROCESSSTART = 1607;                         //UINT_1*E40 PJ create process start
    public const int E40_PJ_CREATE_SLOT_ID_1 = 1701;                              //UINT_1*E40 PJ create slot ID 1 
    public const int E40_PJ_CREATE_SLOT_ID_2 = 1702;                              //UINT_1*E40 PJ create slot ID 2
    public const int E40_PJ_CREATE_SLOT_ID_3 = 1703;                              //UINT_1*E40 PJ create slot ID 3
    public const int E40_PJ_CREATE_SLOT_ID_4 = 1704;                              //UINT_1*E40 PJ create slot ID 4
    public const int E40_PJ_CREATE_SLOT_ID_5 = 1705;                              //UINT_1*E40 PJ create slot ID 5
    public const int E40_PJ_CREATE_SLOT_ID_6 = 1706;                              //UINT_1*E40 PJ create slot ID 6
    public const int E40_PJ_CREATE_SLOT_ID_7 = 1707;                              //UINT_1*E40 PJ create slot ID 7
    public const int E40_PJ_CREATE_SLOT_ID_8 = 1708;                              //UINT_1*E40 PJ create slot ID 8
    public const int E40_PJ_CREATE_SLOT_ID_9 = 1709;                              //UINT_1*E40 PJ create slot ID 9
    public const int E40_PJ_CREATE_SLOT_ID_10 = 1710;                             //UINT_1*E40 PJ create slot ID 10
    public const int E40_PJ_CREATE_SLOT_ID_11 = 1711;                             //UINT_1*E40 PJ create slot ID 11
    public const int E40_PJ_CREATE_SLOT_ID_12 = 1712;                             //UINT_1*E40 PJ create slot ID 12
    public const int E40_PJ_CREATE_SLOT_ID_13 = 1713;                             //UINT_1*E40 PJ create slot ID 13
    public const int E40_PJ_CREATE_SLOT_ID_14 = 1714;                             //UINT_1*E40 PJ create slot ID 14
    public const int E40_PJ_CREATE_SLOT_ID_15 = 1715;                             //UINT_1*E40 PJ create slot ID 15
    public const int E40_PJ_CREATE_SLOT_ID_16 = 1716;                             //UINT_1*E40 PJ create slot ID 16
    public const int E40_PJ_CREATE_SLOT_ID_17 = 1717;                             //UINT_1*E40 PJ create slot ID 17
    public const int E40_PJ_CREATE_SLOT_ID_18 = 1718;                             //UINT_1*E40 PJ create slot ID 18
    public const int E40_PJ_CREATE_SLOT_ID_19 = 1719;                             //UINT_1*E40 PJ create slot ID 19
    public const int E40_PJ_CREATE_SLOT_ID_20 = 1720;                             //UINT_1*E40 PJ create slot ID 20
    public const int E40_PJ_CREATE_SLOT_ID_21 = 1721;                             //UINT_1*E40 PJ create slot ID 21
    public const int E40_PJ_CREATE_SLOT_ID_22 = 1722;                             //UINT_1*E40 PJ create slot ID 22
    public const int E40_PJ_CREATE_SLOT_ID_23 = 1723;                             //UINT_1*E40 PJ create slot ID 23
    public const int E40_PJ_CREATE_SLOT_ID_24 = 1724;                             //UINT_1*E40 PJ create slot ID 24
    public const int E40_PJ_CREATE_SLOT_ID_25 = 1725;                             //UINT_1*E40 PJ create slot ID 25
                                                                                  //* E94  received data area======================
    public const int E94_CJ_CREATE_OBJID = 1801;                                  //ASCII     *E94 CJ create OBJID
    public const int E94_CJ_CREATE_PRCTRLSPEC_QUANTITY = 1802;                    //UINT_1*E94 CJ ProcessingCtrlSpec Quantity 
    public const int E94_CJ_CREATE_PROCESS_ORDER_MGMT = 1804;                     //UINT_1*E94 CJ create ProcessOrderMgmt
    public const int E94_PJ_CREATE_START_METHOD = 1805;                           //UINT_1*E94 CJ create StartMethod

    public const int E94_CJ_CREATE_CARRIERINPUTSPEC_QUANTITY = 1806;              //UINT_1 *E94 CJ CarrierInputSpec Quantity 	
    public const int E94_CJ_CREATE_MTRLOUTSPEC_QUANTITY = 1807;                   //UINT_1 *E94 CJ MtrlOutSpec Quantity 	

    public const int E94_CJ_CREATE_PRCTRLSPEC_PRJOBID_1 = 1811;                   //ASCII*E94CJ ProcessingCtrlSpec PrJobID 1
    public const int E94_CJ_CREATE_PRCTRLSPEC_PRJOBID_2 = 1812;                   //ASCII*E94CJ ProcessingCtrlSpec PrJobID 2
    public const int E94_CJ_CREATE_PRCTRLSPEC_PRJOBID_3 = 1813;                   //ASCII*E94CJ ProcessingCtrlSpec PrJobID 3
    public const int E94_CJ_CREATE_PRCTRLSPEC_PRJOBID_4 = 1814;                   //ASCII*E94CJ ProcessingCtrlSpec PrJobID 4
    public const int E94_CJ_CREATE_PRCTRLSPEC_PRJOBID_5 = 1815;                   //ASCII*E94CJ ProcessingCtrlSpec PrJobID 5
    public const int E94_CJ_CREATE_PRCTRLSPEC_PRJOBID_6 = 1816;                   //ASCII*E94CJ ProcessingCtrlSpec PrJobID 6
    public const int E94_CJ_CREATE_PRCTRLSPEC_PRJOBID_7 = 1817;                   //ASCII*E94CJ ProcessingCtrlSpec PrJobID 7
    public const int E94_CJ_CREATE_PRCTRLSPEC_PRJOBID_8 = 1818;                   //ASCII*E94CJ ProcessingCtrlSpec PrJobID 8

    public const int E94_CJ_CREATE_INPUT_CARRIERID_1 = 1861;                      //ASCII*E94 CJ CarrierInputSpec CarrierID 1	
    public const int E94_CJ_CREATE_INPUT_CARRIERID_2 = 1862;                      //ASCII*E94 CJ CarrierInputSpec CarrierID 2	
    public const int E94_CJ_CREATE_INPUT_CARRIERID_3 = 1863;                      //ASCII*E94 CJ CarrierInputSpec CarrierID 3	
    public const int E94_CJ_CREATE_INPUT_CARRIERID_4 = 1864;                      //ASCII*E94 CJ CarrierInputSpec CarrierID 4	
    public const int E94_CJ_CREATE_INPUT_CARRIERID_5 = 1865;                      //ASCII*E94 CJ CarrierInputSpec CarrierID 5	
    public const int E94_CJ_CREATE_INPUT_CARRIERID_6 = 1866;                      //ASCII*E94 CJ CarrierInputSpec CarrierID 6	
    public const int E94_CJ_CREATE_INPUT_CARRIERID_7 = 1867;                      //ASCII*E94 CJ CarrierInputSpec CarrierID 7	
    public const int E94_CJ_CREATE_INPUT_CARRIERID_8 = 1868;                      //ASCII*E94 CJ CarrierInputSpec CarrierID 8	
    public const int E94_CJ_CREATE_OUTPUT_SRC_CARRIERID_1 = 1871;                 //ASCII*E94 CJ MtrlOutSpec Source CarrierID 1	
    public const int E94_CJ_CREATE_OUTPUT_SRC_CARRIERID_2 = 1872;                 //ASCII*E94 CJ MtrlOutSpec Source CarrierID 2	
    public const int E94_CJ_CREATE_OUTPUT_SRC_CARRIERID_3 = 1873;                 //ASCII*E94 CJ MtrlOutSpec Source CarrierID 3	
    public const int E94_CJ_CREATE_OUTPUT_SRC_CARRIERID_4 = 1874;                 //ASCII*E94 CJ MtrlOutSpec Source CarrierID 4	
    public const int E94_CJ_CREATE_OUTPUT_DST_CARRIERID_1 = 1875;                 //ASCII*E94 CJ MtrlOutSpec Destinatio CarrierID 1	
    public const int E94_CJ_CREATE_OUTPUT_DST_CARRIERID_2 = 1876;                 //ASCII*E94 CJ MtrlOutSpec Destinatio CarrierID 2	
    public const int E94_CJ_CREATE_OUTPUT_DST_CARRIERID_3 = 1877;                 //ASCII*E94 CJ MtrlOutSpec Destinatio CarrierID 3	
    public const int E94_CJ_CREATE_OUTPUT_DST_CARRIERID_4 = 1878;                 //ASCII*E94 CJ MtrlOutSpec Destinatio CarrierID 4	


    // EConst ID 
    public const int GEM_INIT_COMM_STATE = 7;    //UINT_1    GemInitCommState
    public const int GEM_INIT_CONTROL_STATE = 8; //UINT_1    GemInitControlState
    public const int GEM_WBIT_S5 = 21;           //UINT_1    GemWBitS5
    public const int GEM_WBIT_S6 = 22;           //UINT_1    GemWBitS6
    public const int GEM_WBIT_S10 = 23;          //UINT_1    GemWBitS10
    public const int GEM_ESTAB_COMM_DELAY = 44;  //UINT_2    GemEstabCommDelay
    public const int GEM_OFF_LINE_SUBSTATE = 49; //UINT_1    GemOffLineSubstate
    public const int GEM_ON_LINE_FAILED = 50;    //UINT_1    GemOnlineFailed
    public const int GEM_ON_LINE_SUBSTATE = 51;  //UINT_1    GemOnLineSubstate
    public const int GEM_MAX_SPOOL_TRANSMIT = 52;                                 //UINT_4GemMaxSpoolTransmit
    public const int GEM_CONFIG_SPOOL = 66;      //UINT_1    GemConfigSpool
    public const int GEM_OVER_WRITE_SPOOL = 67;  //BOOLEAN   GemOverWriteSpool
    public const int GEM_TIME_FORMAT = 68;       //UINT_1    GemTimeFormat
    public const int GEM_DATAID_FORMAT = 71;     //UINT_1    GemDATAIDFormat
    public const int GEM_SAMPLN_FORMAT = 75;     //UINT_1    GemSAMPLNFormat

}